GET http://localhost:5154/
###
GET http://localhost:5154/students/1005
###
POST http://localhost:5154/students
Content-Type: application/json

{
    "edp": 1005,
    "name": "Benito S. Ambot",
    "year": 1,
    "course": "BSCE"
}
###
GET http://localhost:5154/students

###
DELETE http://localhost:5154/students/1005